### ISSUE TITLE
Issue with running npm commands on windows.

### ISSUE THREAD

**Issue by k-harker** [benrei/env-path#1]
Thanks for this module.  We are starting to use it in our projects to help with default environment variables for local development.

When developing on Windows, we are having difficulty with some commands.  Since env-path is using spawnSync when calling npm or npx on Windows it won't work unless you put npm.cmd.  Today it just returns an ENOENT error.  In order to address this, you should use "shell: true" in the options being passed to spawnSync.  Doing that seems to work well.

[spawnSync documentation about running cmd files](https://nodejs.org/api/child_process.html#child_process_spawning_bat_and_cmd_files_on_windows)

While finding this issue I noticed that these ENOENT errors aren't getting output.  Adding the code below after the call to spawnSync should allow someone to see what's happening.

```
if (res.error) {
  console.log(res.error);
}
```

**Comment by benrei** [comment]
@k-harker Thanks! I had a look at the PR. Will merge it into master
